### ISSUE TITLE
ScrollBar rework

### ISSUE THREAD

**Issue by Lord-KA** [mishaglik/Elpidifor-s-legacy#15]
For now, the interface of scrollBar (actually a slider)
```
    extern "C" uint64_t createScrollbar(int32_t x, int32_t y, uint32_t w, uint32_t h, int32_t maxValue, int32_t startValue);
```
is quite confusing, as I understand it, slider goes from `0` to `maxValue` and is set to `startValue` when created. I think that lower bound is as important as upper, thus interface should be 

```
    extern "C" uint64_t createScrollbar(size_t x, size_t y, size_t w, size_t h, int min, int max, int cur = 0)
```

or something like that.

**Comment by mishaglik** [comment]
I think the same.

**Comment by mishaglik** [comment]
Should we assume ```max >= min```?  Or if max < min invert work of slider?

**Comment by mishaglik** [comment]
Ok. Will assume min < max.

**Comment by Lord-KA** [comment]
Lets write in doc that `min >= max` is UB.

**Comment by mishaglik** [comment]
Resoled
