### ISSUE TITLE
Image::putPixel() has senseless argument types

### ISSUE THREAD

**Issue by XDLoLiK** [mishaglik/Elpidifor-s-legacy#6]
There is no reason for arguments of Image::putPixel() to be int32_t as all the other 
pixel manipulation related functions use uint32_t.

**Comment by Lord-KA** [comment]
I agree with that. There is no reason to have signed coordinate integers, let's replace them with `size_t`, as bitness doesn't matter either.

**Comment by Lord-KA** [comment]
More on that, it could be a good idea to have `using color = uint32_t;`, to make code a bit more readable.

**Comment by Lord-KA** [comment]
```
        /**
         * @brief Get the Pixel object
         * 
         * @param x - x coord. Must be less than width
         * @param y - y coord. Must be less than height
         * @return uint32_t - color of pixel
         */
        virtual uint32_t getPixel(int32_t x, int32_t y) = 0;
 ```
 
 Mistake in description, negative coords are UB.

**Comment by mishaglik** [comment]
Change to size_t.

**Comment by mishaglik** [comment]
Resolved
